version: 2
jobs:
  build:
    environment:
      BASH_ENV: "~/.nix-profile/etc/profile.d/nix.sh"
      
    machine: true

    steps:
      - checkout

      - run: git config --global user.email "travis-ci@example.com"
      - run: git config --global user.name "Travis-CI"

      - run:
          command: echo "Yes" | ./try-reflex --command "exit 0"
          no_output_timeout: 3600

      - run: ./benchmark
      - run: ./test -j 2
